=== Benjole/LEAF/macros/config/Configuration.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT Configuration (InputDatasets,AdditionalVariables)>
<!ATTLIST Configuration
    TargetLumi           CDATA            #REQUIRED
    OutputDirectory      CDATA            #REQUIRED
    PostFix              CDATA            ""
    AnalysisTool         CDATA            #REQUIRED
>

<!ELEMENT InputDatasets (Dataset+)>

<!ELEMENT Dataset EMPTY>
<!ATTLIST Dataset
    Name        CDATA       #REQUIRED
    Lumi        CDATA       #REQUIRED
    Type        CDATA       #REQUIRED
    File        CDATA       #REQUIRED
>


<!ELEMENT AnalysisTool EMPTY>
<!ATTLIST AnalysisTool
    Name        CDATA       #REQUIRED
>

<!ELEMENT AdditionalVariables (Variable*)>

<!ELEMENT Variable EMPTY>
<!ATTLIST Variable
    Name        CDATA       #REQUIRED
    Value       CDATA       #REQUIRED
>

=== Benjole/LEAF/macros/config/GenLevel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configuration PUBLIC "" "Configuration.dtd"[


<!ENTITY TargetLumi  "1" >
<!ENTITY T2Path      "root://t3dcachedb03.psi.ch//pnfs/psi.ch/cms/trivcat/store/user/areimers/UL17/Tuples_GENSIM/LQDM" >
<!-- <!ENTITY infilepath  "/work/areimers/Tuples/LQDM/GENSIM" > -->
<!ENTITY infilepath  "&T2Path;" >
<!ENTITY outfilepath "/work/areimers/LQDM/GENSIM/analysisfiles" >


<!ENTITY LQDM_MLQ600_MX220_MDM200_L1p0  "&infilepath;/LQDM_MLQ600_MX220_MDM200_L1p0/Tuples_GENSIM.root"  >
<!ENTITY LQDM_MLQ700_MX275_MDM250_L1p0  "&infilepath;/LQDM_MLQ700_MX275_MDM250_L1p0/Tuples_GENSIM.root"  >
<!ENTITY LQDM_MLQ800_MX330_MDM300_L1p0  "&infilepath;/LQDM_MLQ800_MX330_MDM300_L1p0/Tuples_GENSIM.root"  >
<!ENTITY LQDM_MLQ900_MX385_MDM350_L1p0  "&infilepath;/LQDM_MLQ900_MX385_MDM350_L1p0/Tuples_GENSIM.root"  >
<!ENTITY LQDM_MLQ1000_MX440_MDM400_L1p0 "&infilepath;/LQDM_MLQ1000_MX440_MDM400_L1p0/Tuples_GENSIM.root" >
<!ENTITY LQDM_MLQ1100_MX495_MDM450_L1p0 "&infilepath;/LQDM_MLQ1100_MX495_MDM450_L1p0/Tuples_GENSIM.root" >
<!ENTITY LQDM_MLQ1200_MX550_MDM500_L1p0 "&infilepath;/LQDM_MLQ1200_MX550_MDM500_L1p0/Tuples_GENSIM.root" >
<!ENTITY LQDM_MLQ1300_MX605_MDM550_L1p0 "&infilepath;/LQDM_MLQ1300_MX605_MDM550_L1p0/Tuples_GENSIM.root" >
<!ENTITY LQDM_MLQ1400_MX660_MDM600_L1p0 "&infilepath;/LQDM_MLQ1400_MX660_MDM600_L1p0/Tuples_GENSIM.root" >
<!ENTITY LQDM_MLQ1500_MX715_MDM650_L1p0 "&infilepath;/LQDM_MLQ1500_MX715_MDM650_L1p0/Tuples_GENSIM.root" >
<!ENTITY LQDM_MLQ1600_MX770_MDM700_L1p0 "&infilepath;/LQDM_MLQ1600_MX770_MDM700_L1p0/Tuples_GENSIM.root" >
<!ENTITY LQDM_MLQ1700_MX825_MDM750_L1p0 "&infilepath;/LQDM_MLQ1700_MX825_MDM750_L1p0/Tuples_GENSIM.root" >
<!ENTITY LQDM_MLQ1800_MX880_MDM800_L1p0 "&infilepath;/LQDM_MLQ1800_MX880_MDM800_L1p0/Tuples_GENSIM.root" >
<!ENTITY LQDM_MLQ1900_MX935_MDM850_L1p0 "&infilepath;/LQDM_MLQ1900_MX935_MDM850_L1p0/Tuples_GENSIM.root" >
<!ENTITY LQDM_MLQ2000_MX990_MDM900_L1p0 "&infilepath;/LQDM_MLQ2000_MX990_MDM900_L1p0/Tuples_GENSIM.root" >

]>


<Configuration OutputDirectory="&outfilepath;" PostFix="" TargetLumi="&TargetLumi;" AnalysisTool="GenlevelTool">
    <InputDatasets>
        <Dataset Name="LQDM_MLQ600_MX220_MDM200_L1p0"  Lumi="1.74317e+06" Type="MC" File="&LQDM_MLQ600_MX220_MDM200_L1p0;" />
        <Dataset Name="LQDM_MLQ700_MX275_MDM250_L1p0"  Lumi="4.64684e+06" Type="MC" File="&LQDM_MLQ700_MX275_MDM250_L1p0;" />
        <Dataset Name="LQDM_MLQ800_MX330_MDM300_L1p0"  Lumi="1.11940e+07" Type="MC" File="&LQDM_MLQ800_MX330_MDM300_L1p0;" />
        <Dataset Name="LQDM_MLQ900_MX385_MDM350_L1p0"  Lumi="2.52313e+07" Type="MC" File="&LQDM_MLQ900_MX385_MDM350_L1p0;" />
        <Dataset Name="LQDM_MLQ1000_MX440_MDM400_L1p0" Lumi="5.42495e+07" Type="MC" File="&LQDM_MLQ1000_MX440_MDM400_L1p0;"/>
        <Dataset Name="LQDM_MLQ1100_MX495_MDM450_L1p0" Lumi="1.10947e+08" Type="MC" File="&LQDM_MLQ1100_MX495_MDM450_L1p0;"/>
        <Dataset Name="LQDM_MLQ1200_MX550_MDM500_L1p0" Lumi="2.22883e+08" Type="MC" File="&LQDM_MLQ1200_MX550_MDM500_L1p0;"/>
        <Dataset Name="LQDM_MLQ1300_MX605_MDM550_L1p0" Lumi="4.29984e+08" Type="MC" File="&LQDM_MLQ1300_MX605_MDM550_L1p0;"/>
        <Dataset Name="LQDM_MLQ1400_MX660_MDM600_L1p0" Lumi="8.22594e+08" Type="MC" File="&LQDM_MLQ1400_MX660_MDM600_L1p0;"/>
        <Dataset Name="LQDM_MLQ1500_MX715_MDM650_L1p0" Lumi="1.53374e+09" Type="MC" File="&LQDM_MLQ1500_MX715_MDM650_L1p0;"/>
        <Dataset Name="LQDM_MLQ1600_MX770_MDM700_L1p0" Lumi="2.81162e+09" Type="MC" File="&LQDM_MLQ1600_MX770_MDM700_L1p0;"/>
        <Dataset Name="LQDM_MLQ1700_MX825_MDM750_L1p0" Lumi="5.10812e+09" Type="MC" File="&LQDM_MLQ1700_MX825_MDM750_L1p0;"/>
        <Dataset Name="LQDM_MLQ1800_MX880_MDM800_L1p0" Lumi="9.23077e+09" Type="MC" File="&LQDM_MLQ1800_MX880_MDM800_L1p0;"/>
        <Dataset Name="LQDM_MLQ1900_MX935_MDM850_L1p0" Lumi="1.64024e+10" Type="MC" File="&LQDM_MLQ1900_MX935_MDM850_L1p0;"/>
        <Dataset Name="LQDM_MLQ2000_MX990_MDM900_L1p0" Lumi="2.91545e+10" Type="MC" File="&LQDM_MLQ2000_MX990_MDM900_L1p0;"/>
    </InputDatasets>

    <AdditionalVariables>
        <Variable Name="test" Value="testvalue"/>
    </AdditionalVariables>
</Configuration>

=== Benjole/LEAF/macros/config/GenLevel_ChiPsi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configuration PUBLIC "" "Configuration.dtd"[


<!ENTITY TargetLumi  "1" >
<!ENTITY outfilepath "/work/areimers/LQDM/GENSIM/analysisfiles" >


<!ENTITY LQLQToBTau_MLQ1000_MPS574_MC1427_L1p0        SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/LQLQToBTau_MLQ1000_MPS574_MC1427_L1p0.xml"        >
<!ENTITY LQLQToBTau_MLQ1000_MPS983_MC1912_L1p0        SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/LQLQToBTau_MLQ1000_MPS983_MC1912_L1p0.xml"        >
<!ENTITY LQLQToBTau_MLQ1900_MPS475_MC1427_L1p0        SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/LQLQToBTau_MLQ1900_MPS475_MC1427_L1p0.xml"        >
<!ENTITY LQLQToBTau_MLQ1900_MPS1064_MC1794_L1p0       SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/LQLQToBTau_MLQ1900_MPS1064_MC1794_L1p0.xml"       >
<!ENTITY LQLQToBTauPsiChi_MLQ1000_MPS574_MC1427_L1p0  SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/LQLQToBTauPsiChi_MLQ1000_MPS574_MC1427_L1p0.xml"  >
<!ENTITY LQLQToBTauPsiChi_MLQ1900_MPS475_MC1427_L1p0  SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/LQLQToBTauPsiChi_MLQ1900_MPS475_MC1427_L1p0.xml"  >
<!ENTITY LQLQToBTauPsiChi_MLQ1900_MPS1064_MC1794_L1p0 SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/LQLQToBTauPsiChi_MLQ1900_MPS1064_MC1794_L1p0.xml" >
<!ENTITY LQLQToPsiChi_MLQ1000_MPS574_MC1427_L1p0      SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/LQLQToPsiChi_MLQ1000_MPS574_MC1427_L1p0.xml"      >
<!ENTITY LQLQToPsiChi_MLQ1900_MPS475_MC1427_L1p0      SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/LQLQToPsiChi_MLQ1900_MPS475_MC1427_L1p0.xml"      >
<!ENTITY LQLQToPsiChi_MLQ1900_MPS1064_MC1794_L1p0     SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/LQLQToPsiChi_MLQ1900_MPS1064_MC1794_L1p0.xml"     >
<!ENTITY PsiPsiToLQChi_MLQ1000_MPS574_MC1427_L1p0     SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/PsiPsiToLQChi_MLQ1000_MPS574_MC1427_L1p0.xml"     >
<!ENTITY PsiPsiToLQChi_MLQ1000_MPS983_MC1912_L1p0     SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/PsiPsiToLQChi_MLQ1000_MPS983_MC1912_L1p0.xml"     >
<!ENTITY PsiPsiToLQChi_MLQ1900_MPS475_MC1427_L1p0     SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/PsiPsiToLQChi_MLQ1900_MPS475_MC1427_L1p0.xml"     >
<!ENTITY PsiPsiToLQChi_MLQ1900_MPS1064_MC1794_L1p0    SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/PsiPsiToLQChi_MLQ1900_MPS1064_MC1794_L1p0.xml"    >

]>


<Configuration OutputDirectory="&outfilepath;" PostFix="" TargetLumi="&TargetLumi;" AnalysisTool="GenlevelTool">
    <InputDatasets>
<!--
        <Dataset Name="LQLQToBTau_MLQ1000_MPS574_MC1427_L1p0"         Lumi="100000"  Type="MC" >
            &LQLQToBTau_MLQ1000_MPS574_MC1427_L1p0;
        </Dataset>

        <Dataset Name="LQLQToBTau_MLQ1000_MPS983_MC1912_L1p0"         Lumi="100000"  Type="MC" >
            &LQLQToBTau_MLQ1000_MPS983_MC1912_L1p0;
        </Dataset>
-->
        <Dataset Name="LQLQToBTau_MLQ1900_MPS475_MC1427_L1p0"         Lumi="100000"  Type="MC" >
            &LQLQToBTau_MLQ1900_MPS475_MC1427_L1p0;
        </Dataset>
<!--
        <Dataset Name="LQLQToBTau_MLQ1900_MPS1064_MC1794_L1p0"        Lumi="100000"  Type="MC" >
            &LQLQToBTau_MLQ1900_MPS1064_MC1794_L1p0;
        </Dataset>

        <Dataset Name="LQLQToBTauPsiChi_MLQ1000_MPS574_MC1427_L1p0"   Lumi="100000"  Type="MC" >
            &LQLQToBTauPsiChi_MLQ1000_MPS574_MC1427_L1p0;
        </Dataset>
-->
        <Dataset Name="LQLQToBTauPsiChi_MLQ1900_MPS475_MC1427_L1p0"   Lumi="100000"  Type="MC" >
            &LQLQToBTauPsiChi_MLQ1900_MPS475_MC1427_L1p0;
        </Dataset>
<!--
        <Dataset Name="LQLQToBTauPsiChi_MLQ1900_MPS1064_MC1794_L1p0"  Lumi="100000"  Type="MC" >
            &LQLQToBTauPsiChi_MLQ1900_MPS1064_MC1794_L1p0;
        </Dataset>

        <Dataset Name="LQLQToPsiChi_MLQ1000_MPS574_MC1427_L1p0"       Lumi="100000"  Type="MC" >
            &LQLQToPsiChi_MLQ1000_MPS574_MC1427_L1p0;
        </Dataset>
-->
        <Dataset Name="LQLQToPsiChi_MLQ1900_MPS475_MC1427_L1p0"       Lumi="100000"  Type="MC" >
            &LQLQToPsiChi_MLQ1900_MPS475_MC1427_L1p0;
        </Dataset>
<!--
        <Dataset Name="LQLQToPsiChi_MLQ1900_MPS1064_MC1794_L1p0"      Lumi="100000"  Type="MC" >
            &LQLQToPsiChi_MLQ1900_MPS1064_MC1794_L1p0;
        </Dataset>

        <Dataset Name="PsiPsiToLQChi_MLQ1000_MPS574_MC1427_L1p0"      Lumi="100000"  Type="MC" >
            &PsiPsiToLQChi_MLQ1000_MPS574_MC1427_L1p0;
        </Dataset>

        <Dataset Name="PsiPsiToLQChi_MLQ1000_MPS983_MC1912_L1p0"      Lumi="100000"  Type="MC" >
            &PsiPsiToLQChi_MLQ1000_MPS983_MC1912_L1p0;
        </Dataset>
-->
        <Dataset Name="PsiPsiToLQChi_MLQ1900_MPS475_MC1427_L1p0"      Lumi="100000"  Type="MC" >
            &PsiPsiToLQChi_MLQ1900_MPS475_MC1427_L1p0;
        </Dataset>
<!--
        <Dataset Name="PsiPsiToLQChi_MLQ1900_MPS1064_MC1794_L1p0"     Lumi="100000"  Type="MC" >
            &PsiPsiToLQChi_MLQ1900_MPS1064_MC1794_L1p0;
        </Dataset>
-->
    </InputDatasets>

    <AdditionalVariables>
        <Variable Name="test" Value="testvalue"/>
    </AdditionalVariables>
</Configuration>

=== Benjole/LEAF/macros/config/Preselection.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configuration PUBLIC "" "Configuration.dtd"[


<!ENTITY TargetLumi  "1" >
<!ENTITY outfilepath "/work/areimers/LQDM/UL17/Preselection" >


<!ENTITY LQLQToBTau_MLQ1000_MPS574_MC1427_L1p0        SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/LQLQToBTau_MLQ1000_MPS574_MC1427_L1p0.xml"        >
<!ENTITY LQLQToBTau_MLQ1000_MPS983_MC1912_L1p0        SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/LQLQToBTau_MLQ1000_MPS983_MC1912_L1p0.xml"        >
<!ENTITY LQLQToBTau_MLQ1900_MPS475_MC1427_L1p0        SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/LQLQToBTau_MLQ1900_MPS475_MC1427_L1p0.xml"        >
<!ENTITY LQLQToBTau_MLQ1900_MPS1064_MC1794_L1p0       SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/LQLQToBTau_MLQ1900_MPS1064_MC1794_L1p0.xml"       >
<!ENTITY LQLQToBTauPsiChi_MLQ1000_MPS574_MC1427_L1p0  SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/LQLQToBTauPsiChi_MLQ1000_MPS574_MC1427_L1p0.xml"  >
<!ENTITY LQLQToBTauPsiChi_MLQ1900_MPS475_MC1427_L1p0  SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/LQLQToBTauPsiChi_MLQ1900_MPS475_MC1427_L1p0.xml"  >
<!ENTITY LQLQToBTauPsiChi_MLQ1900_MPS1064_MC1794_L1p0 SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/LQLQToBTauPsiChi_MLQ1900_MPS1064_MC1794_L1p0.xml" >
<!ENTITY LQLQToPsiChi_MLQ1000_MPS574_MC1427_L1p0      SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/LQLQToPsiChi_MLQ1000_MPS574_MC1427_L1p0.xml"      >
<!ENTITY LQLQToPsiChi_MLQ1900_MPS475_MC1427_L1p0      SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/LQLQToPsiChi_MLQ1900_MPS475_MC1427_L1p0.xml"      >
<!ENTITY LQLQToPsiChi_MLQ1900_MPS1064_MC1794_L1p0     SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/LQLQToPsiChi_MLQ1900_MPS1064_MC1794_L1p0.xml"     >
<!ENTITY PsiPsiToLQChi_MLQ1000_MPS574_MC1427_L1p0     SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/PsiPsiToLQChi_MLQ1000_MPS574_MC1427_L1p0.xml"     >
<!ENTITY PsiPsiToLQChi_MLQ1000_MPS983_MC1912_L1p0     SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/PsiPsiToLQChi_MLQ1000_MPS983_MC1912_L1p0.xml"     >
<!ENTITY PsiPsiToLQChi_MLQ1900_MPS475_MC1427_L1p0     SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/PsiPsiToLQChi_MLQ1900_MPS475_MC1427_L1p0.xml"     >
<!ENTITY PsiPsiToLQChi_MLQ1900_MPS1064_MC1794_L1p0    SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/PsiPsiToLQChi_MLQ1900_MPS1064_MC1794_L1p0.xml"    >
<!ENTITY test    SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/test.xml"    >
<!ENTITY testt3local    SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/testt3local.xml"    >
<!ENTITY testt3    SYSTEM "/work/areimers/LQDM/macros/datasets/UL17/Recolevel/testt3.xml"    >

]>


<Configuration OutputDirectory="&outfilepath;" PostFix="" TargetLumi="&TargetLumi;" AnalysisTool="PreselectionTool">
    <InputDatasets>

        <Dataset Name="LQLQToBTau_MLQ1000_MPS574_MC1427_L1p0"         Lumi="100000"  Type="MC" >
            &LQLQToBTau_MLQ1000_MPS574_MC1427_L1p0;
        </Dataset>
        <Dataset Name="LQLQToBTau_MLQ1000_MPS983_MC1912_L1p0"         Lumi="100000"  Type="MC" >
            &LQLQToBTau_MLQ1000_MPS983_MC1912_L1p0;
        </Dataset>
        <Dataset Name="LQLQToBTau_MLQ1900_MPS475_MC1427_L1p0"         Lumi="100000"  Type="MC" >
            &LQLQToBTau_MLQ1900_MPS475_MC1427_L1p0;
        </Dataset>
        <Dataset Name="LQLQToBTau_MLQ1900_MPS1064_MC1794_L1p0"        Lumi="100000"  Type="MC" >
            &LQLQToBTau_MLQ1900_MPS1064_MC1794_L1p0;
        </Dataset>
        <Dataset Name="LQLQToBTauPsiChi_MLQ1000_MPS574_MC1427_L1p0"   Lumi="100000"  Type="MC" >
            &LQLQToBTauPsiChi_MLQ1000_MPS574_MC1427_L1p0;
        </Dataset>
        <Dataset Name="LQLQToBTauPsiChi_MLQ1900_MPS475_MC1427_L1p0"   Lumi="100000"  Type="MC" >
            &LQLQToBTauPsiChi_MLQ1900_MPS475_MC1427_L1p0;
        </Dataset>
        <Dataset Name="LQLQToBTauPsiChi_MLQ1900_MPS1064_MC1794_L1p0"  Lumi="100000"  Type="MC" >
            &LQLQToBTauPsiChi_MLQ1900_MPS1064_MC1794_L1p0;
        </Dataset>
        <Dataset Name="LQLQToPsiChi_MLQ1000_MPS574_MC1427_L1p0"       Lumi="100000"  Type="MC" >
            &LQLQToPsiChi_MLQ1000_MPS574_MC1427_L1p0;
        </Dataset>
        <Dataset Name="LQLQToPsiChi_MLQ1900_MPS475_MC1427_L1p0"       Lumi="100000"  Type="MC" >
            &LQLQToPsiChi_MLQ1900_MPS475_MC1427_L1p0;
        </Dataset>
        <Dataset Name="LQLQToPsiChi_MLQ1900_MPS1064_MC1794_L1p0"      Lumi="100000"  Type="MC" >
            &LQLQToPsiChi_MLQ1900_MPS1064_MC1794_L1p0;
        </Dataset>
        <Dataset Name="PsiPsiToLQChi_MLQ1000_MPS574_MC1427_L1p0"      Lumi="100000"  Type="MC" >
            &PsiPsiToLQChi_MLQ1000_MPS574_MC1427_L1p0;
        </Dataset>
        <Dataset Name="PsiPsiToLQChi_MLQ1000_MPS983_MC1912_L1p0"      Lumi="100000"  Type="MC" >
            &PsiPsiToLQChi_MLQ1000_MPS983_MC1912_L1p0;
        </Dataset>
        <Dataset Name="PsiPsiToLQChi_MLQ1900_MPS475_MC1427_L1p0"      Lumi="100000"  Type="MC" >
            &PsiPsiToLQChi_MLQ1900_MPS475_MC1427_L1p0;
        </Dataset>
        <Dataset Name="PsiPsiToLQChi_MLQ1900_MPS1064_MC1794_L1p0"     Lumi="100000"  Type="MC" >
            &PsiPsiToLQChi_MLQ1900_MPS1064_MC1794_L1p0;
        </Dataset>
        <!-- <Dataset Name="test"     Lumi="100000"  Type="MC" >
            &test;
        </Dataset>
        <Dataset Name="testt3local"     Lumi="100000"  Type="MC" >
            &testt3local;
        </Dataset>
        <Dataset Name="testt3"     Lumi="100000"  Type="MC" >
            &testt3;
        </Dataset> -->

    </InputDatasets>

    <AdditionalVariables>
        <Variable Name="test" Value="testvalue"/>
    </AdditionalVariables>
</Configuration>

=== Benjole/LEAF/Analyzer/templates/config_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configuration PUBLIC "" "Configuration.dtd"[


<!ENTITY TargetLumi  "1" >
<!ENTITY outfilepath "/pnfs/psi.ch/cms/trivcat/store/user/$MYUSERNAME/$MYANALYSISNAME/2017/Preselection/InitialSetup" >


<!ENTITY LQLQToBTau_MLQ1000_MPS117_MC1100_L1p0   SYSTEM "$MYANALYZERPATH/datasets/UL17/Summer20/MINIAOD/LQLQToBTau_MLQ1000_MPS117_MC1100_L1p0.xml" >
<!ENTITY LQLQToBTau_MLQ1360_MPS117_MC1100_L1p0   SYSTEM "$MYANALYZERPATH/datasets/UL17/Summer20/MINIAOD/LQLQToBTau_MLQ1360_MPS117_MC1100_L1p0.xml" >
<!ENTITY WJetsToLNu_Inclusive                    SYSTEM "$MYANALYZERPATH/datasets/UL17/Summer20/MINIAOD/WJetsToLNu_Inclusive.xml" >

]>


<Configuration OutputDirectory="&outfilepath;" PostFix="" SEDirector="root://t3dcachedb03.psi.ch/" TargetLumi="&TargetLumi;" AnalysisTool="$MYTOOLNAME">

  <SubmissionSettings EventsPerJob="-1" FilesPerJob="-1" Walltime="01:00:00" />

  <InputDatasets>
    <Dataset Name="LQLQToBTau_MLQ1000_MPS117_MC1100_L1p0"  Lumi="100000"         Year="2017"  Type="MC"  Group="None"  >    &LQLQToBTau_MLQ1000_MPS117_MC1100_L1p0;    </Dataset>
    <Dataset Name="LQLQToBTau_MLQ1360_MPS117_MC1100_L1p0"  Lumi="100000"         Year="2017"  Type="MC"  Group="None"  >    &LQLQToBTau_MLQ1360_MPS117_MC1100_L1p0;    </Dataset>
    <Dataset Name="WJetsToLNu_Inclusive"                   Lumi="19997.57806"    Year="2017"  Type="MC"  Group="WJets" >    &WJetsToLNu_Inclusive;                     </Dataset>
  </InputDatasets>

  <AdditionalVariables>
    <Variable Name="test" Value="testvalue"/>
  </AdditionalVariables>

</Configuration>
